server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  application:
    name: recipes-backend
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    cors:
      allowed-origins: "*"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "Content-Type,Authorization"
      allow-credentials: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${recipes.datasource.url}
    username: ${recipes.datasource.username}
    password: ${recipes.datasource.password}
  jpa:
    hibernate:
      #      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true

  data:
    redis:
      port: ${recipes.redis.port}
      host: ${recipes.redis.host}





logging:
  level:
    org:
      springframework:
        jdbc:
          support:
            org.springframework.jdbc.support.JdbcTransactionManager: debug
    com:
      recipes:
        service: info
        controller: info
        repository: info

python:
  script:
    path: 'Recipes-server/src/main/java/com/recipes/pythonScripts/recommendation.py'

recipes:
  jwt:
    adminSecretKey: myAdminSecretKey123456
    adminTtl: 7200000  # 2 hours
    adminTokenName: Admin-Token
    userSecretKey: myUserSecretKey123456
    userTtl: 86400000  # 1 day
    userTokenName: User-Token



# Springdoc OpenAPI configuration
springdoc:
  swagger-ui:
    path: /springdoc  # Custom path for Swagger UI
    docExpansion: full  # Expand tags and operations by default
    displayRequestDuration: true  # Display request duration
    showExtensions: true  # Show vendor extensions (x- fields)
    showCommonExtensions: true  # Show common parameter extensions
    disable-swagger-default-url: true  # Disable default petstore URL
  api-docs:
    path: /v3/api-docs  # Custom path for API docs
    enabled: true  # Enable the /v3/api-docs endpoint
    resolve-schema-properties: true  # Enable property resolver on @Schema

  group-configs:
    - group: 'default'
      paths-to-match: '/**'  # Match all paths
      packages-to-scan: com.recipes.controller  # Scan this package for controllers

# Knife4j enhanced configuration
knife4j:
  enable: true  # Enable Knife4j enhanced mode
  documents:
    - group: 2.0 Version  # Custom document group name
      name: API Signatures  # Custom document tag name
      locations: classpath:sign/*  # Path to markdown files
  setting:
    #    language: ‘en-US’  # UI default language (English)
    enable-swagger-models: true  # Display Swagger Models feature
    swagger-model-name: API List  # Rename Swagger Model section
    enable-document-manage: true  # Enable document management feature
    enable-version: false  # Disable version control on UI
    enable-reload-cache-parameter: false  # Disable reload cache parameter button
    enable-after-script: true  # Show AfterScript functionality in Debug tab
    enable-filter-multipart-api-method-type: POST  # Filter interface request types to show only POST
    enable-filter-multipart-apis: false  # Do not filter out multipart APIs
    enable-request-cache: true  # Enable request parameter caching
    #    enable-host: false  # Disable custom Host configuration
    enable-host-text: 192.168.0.193:8000  # Set Host address (if enable-host is true)
    enable-home-custom: true  # Enable custom homepage content
    home-custom-path: classpath:markdown/home.md  # Path to custom homepage content in Markdown
    enable-search: false  # Disable search bar in UI
    enable-dynamic-parameter: false  # Disable dynamic parameter debugging
    enable-debug: true  # Enable debug mode
    enable-open-api: true  # Disable OpenAPI display
    enable-group: true  # Display service groups
  cors: false  # Disable default CORS configuration
  production: false  # Disable production environment protection
