recipes:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: simulaterecipes
    username: root
    password: cscscs61B1234
    #    url: jdbc:mysql://localhost:3306/simulaterecipes?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true

  redis:
    host: 127.0.0.1
    port: 6379



