recipes:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: recipes-rds-1.cluq6g4cqy61.eu-west-1.rds.amazonaws.com
    url: jdbc:mysql://recipes-rds-1.cluq6g4cqy61.eu-west-1.rds.amazonaws.com:3306/simulaterecipes
    port: 3306
    database: simulaterecipes
    username: admin
    password: Password1234

  redis:
    host: recipes-redis-s1a59u.serverless.euw1.cache.amazonaws.com:6379
    port: 6379
    # password: <your-redis-password>
